name: Release

on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: asdf_plugin_test
      uses: asdf-vm/actions/plugin-test@v1
      with:
        command: "datree --version"
      env:
        GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }} # automatically provided

  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        with:
          release-type: simple
